"""Port Spotify Basic Pitch (TensorFlow) weights to the PyTorch BasicPitchModel.

Reads the TF saved_model bundled with the installed `basic_pitch` package and
writes `polyddsp/model/weights/bp_pytorch.pth` — the committed checkpoint that
`polyddsp.model.pitch.load_basic_pitch()` loads at runtime. One-shot script:
re-run only when upstream `basic-pitch` ships new weights.

`tensorflow==2.15` and `basic-pitch` are not project dependencies — install them
separately (into a throwaway environment) to run this script. Only installable
where a matching TensorFlow wheel exists. Run with `CUDA_VISIBLE_DEVICES=""` so
TensorFlow stays off the GPU:

    CUDA_VISIBLE_DEVICES="" python scripts/port_basic_pitch.py

The mapping mirrors the deployed TF graph (after dead-branch pruning at save):
the contour `Conv2D(32,(5,5))` outer block in `basic_pitch.models.model` is
silently dropped because its output is overwritten before use, leaving the
deployed model with one effective contour conv. The mapping below targets the
six convs + three BNs that actually exist in the TF saved_model.
"""
from __future__ import annotations

from pathlib import Path

import tensorflow as tf
import torch

from basic_pitch import ICASSP_2022_MODEL_PATH

from polyddsp.model.pitch import BasicPitchModel, WEIGHTS_PATH


CONV_KEY_MAP = {
    # TF conv name → PyTorch module path
    "conv2d_1": "contour_1.0",
    "contours-reduced": "contour_2.0",
    "conv2d_2": "note_1.0",
    "conv2d_3": "note_1.2",
    "conv2d_4": "onset_1.0",
    "conv2d_5": "onset_2.0",
}

BN_KEY_MAP = {
    "batch_normalization": "cqt_bn",
    "batch_normalization_2": "contour_1.1",
    "batch_normalization_3": "onset_1.1",
}


def main() -> None:
    print(f"Loading TF saved_model from {ICASSP_2022_MODEL_PATH}")
    tf_model = tf.saved_model.load(str(ICASSP_2022_MODEL_PATH))
    tf_weights = {v.name: v.numpy() for v in tf_model.variables}

    print("TF variables:")
    for name in sorted(tf_weights):
        print(f"  {name} {tf_weights[name].shape}")

    torch_model = BasicPitchModel()
    base_state = torch_model.state_dict()

    new_state: dict[str, torch.Tensor] = {}

    # Conv2D: TF kernel layout (kernel_h=time, kernel_w=freq, in_ch, out_ch).
    # Our PyTorch convs use (out, in, freq, time), so transpose (3, 2, 1, 0).
    for tf_name, pt_name in CONV_KEY_MAP.items():
        kernel = tf_weights[f"{tf_name}/kernel:0"]
        bias = tf_weights[f"{tf_name}/bias:0"]
        new_state[f"{pt_name}.weight"] = torch.from_numpy(kernel.transpose(3, 2, 1, 0).copy())
        new_state[f"{pt_name}.bias"] = torch.from_numpy(bias.copy())

    for tf_name, pt_name in BN_KEY_MAP.items():
        new_state[f"{pt_name}.weight"] = torch.from_numpy(tf_weights[f"{tf_name}/gamma:0"].copy())
        new_state[f"{pt_name}.bias"] = torch.from_numpy(tf_weights[f"{tf_name}/beta:0"].copy())
        new_state[f"{pt_name}.running_mean"] = torch.from_numpy(tf_weights[f"{tf_name}/moving_mean:0"].copy())
        new_state[f"{pt_name}.running_var"] = torch.from_numpy(tf_weights[f"{tf_name}/moving_variance:0"].copy())
        new_state[f"{pt_name}.num_batches_tracked"] = base_state[f"{pt_name}.num_batches_tracked"]

    # CQT kernels are non-trainable buffers generated by nnAudio at init time.
    # Carry them over from the freshly-instantiated model so the .pth is self-contained.
    for k, v in base_state.items():
        if k.startswith("cqt.") and k not in new_state:
            new_state[k] = v

    # Validate shape match before save.
    for k, v in new_state.items():
        if k not in base_state:
            raise KeyError(f"port produced unknown key {k}")
        if tuple(v.shape) != tuple(base_state[k].shape):
            raise ValueError(f"shape mismatch for {k}: ported {tuple(v.shape)} vs model {tuple(base_state[k].shape)}")
    missing = sorted(set(base_state) - set(new_state))
    if missing:
        raise KeyError(f"port missing keys: {missing}")

    torch_model.load_state_dict(new_state, strict=True)

    out_path = Path(WEIGHTS_PATH)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    torch.save(torch_model.state_dict(), out_path)
    print(f"Wrote {out_path} ({out_path.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
